# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
  - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bxuild"
  backup:
    name: Perform Backup for WP sites
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Install Platform.sh CLI
        run: curl -sS https://platform.sh/cli/installer | php
      - name: Backup Neminis
        run: platform backup:create -p ${{secrets.PSH_PROJECT_NEMINIS}} master
